__author__ = 'Carlos Vigo <carviher1990@gmailcom>'
__email__ = '<carlosv@phys.ethz.ch>'
__short_author__ = 'Carlos Vigo'
__copyright__ = '2022, Carlos Vigo'
__package_name__ = 'beancount-telegram'
__module_name__ = 'beancount_telegram.py'
__project_name__ = 'Beancount Telegram'
__url__ = 'https://github.com/c-vigo/beancount-telegram'
__documentation__ = 'https://github.com/c-vigo/beancount-telegram'
__version__ = '0.1'
__short_version__ = '0.1'
__description__ = 'A chat history archiver for Telegram'

